AWSTemplateFormatVersion: '2010-09-09'

Resources:
  FirstS3:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: 'first-bucket1572885457'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags: 
        - Key: Name
          Value: FirstS3