apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  selector:
    matchLabels:
      app: first-app-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: first-app-proxy
    spec:
      containers:
        - name: server
          image: nginx:1.18.0
          ports:
            - containerPort: 8080