Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1708.01"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", host: 8080, guest: 80
  config.vm.network "forwarded_port", host: 8443, guest: 443

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
