Vagrant.configure(2) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false
  config.vm.box = "centos/7"
  config.vm.box_version = "1708.01"

  config.vm.define "web" do |web|
    web.vm.network :private_network, ip: "192.168.33.51", virtualbox__intnet: "intnet"
  end
  config.vm.define "memcached1" do |memcached1|
    memcached1.vm.network :private_network, ip: "192.168.33.52", virtualbox__intnet: "intnet"
  end
  config.vm.define "memcached2" do |memcached2|
    memcached2.vm.network :private_network, ip: "192.168.33.53", virtualbox__intnet: "intnet"
  end
end