Vagrant.configure(2) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.box_version = "1708.01"
    web.vm.network :private_network, ip: "192.168.33.51"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "forwarded_port", guest: 443, host: 8443
  end
  config.vm.define "memcached1" do |memcached1|
    memcached1.vm.box = "centos/7"
    memcached1.vm.box_version = "1708.01"
    memcached1.vm.network :private_network, ip: "192.168.33.52"
    memcached1.vm.network "forwarded_port", guest: 80, host: 8081
    memcached1.vm.network "forwarded_port", guest: 443, host: 8444
  end
  config.vm.define "memcached2" do |memcached2|
    memcached2.vm.box = "centos/7"
    memcached2.vm.box_version = "1708.01"
    memcached2.vm.network :private_network, ip: "192.168.33.53"
    memcached2.vm.network "forwarded_port", guest: 80, host: 8082
    memcached2.vm.network "forwarded_port", guest: 443, host: 8445
  end
end